
training:
  batch_size: 64
  block_size: 128
  dropout: 0.2
  device: "cuda"
  use_mlflow: True
  
optimizer:
  lr: 0.002
  weight_decay: 0.01

scheduler:
  step_size: 10
  gamma: 0.1


model:
  dropout: 0.2

training_params:
  epochs: 100
  log_interval: 5
  save_interval: 1
  output_dir: "model_output/"
  max_iters : 500
  eval_iters : 5









